.TH STATD 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
statd \- Trivial statistics daemon.
.SH SYNOPSIS
.B statd
.\".I [\-htvm] [\-\-help] [\-\-traditional] [\-\-version] [\-\-mail]
.SH "DESCRIPTION"
Statd is a small daemon to be run from inetd. It reports on CPU-usage when asked.
.SH AUTHOR
This manual page was written by Jakob Borg <jakob@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
.br
