.TH GLCPU 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
glcpu \- Three-dimensional networked system monitor.
.SH SYNOPSIS
.B glcpu
.\".I [\-htvm] [\-\-help] [\-\-traditional] [\-\-version] [\-\-mail]
.SH "DESCRIPTION"
This manual page documents briefly the
.BR glcpu
program.
.PP
The
.B glcpu
can graph the CPU activity of any number of hosts over a network,
using minimal bandwidth.
.SH FILES
.TP
.B .glcpurc
User configuration file. All configuration of glcpu is done here. See glcpurc.sample in the documentation directory for more info.
.SH AUTHOR
This manual page was written by Jakob Borg <jakob@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
.br
